// #[path="operatori si expresii/sum00/sum.rs"] mod sum;
// #[path="operatori si expresii/urare/urare.rs"] mod urare;
// #[path="operatori si expresii/scadere/scadere.rs"] mod scadere;
// #[path="operatori si expresii/asii/asii.rs"] mod asii;
// #[path="operatori si expresii/uciv/uciv.rs"] mod uciv;
// #[path="operatori si expresii/globuri/globuri.rs"] mod globuri;
// #[path="operatori si expresii/copii2/copii2.rs"] mod copii2;
// #[path="operatori si expresii/parc2/parc2.rs"] mod parc2;
// #[path="operatori si expresii/camioane/camioane.rs"] mod camioane;
// #[path="sortarea vectorilor/ordonare/ordonare.rs"] mod ordonare;
// #[path="sortarea vectorilor/sortPrime/sortPrime.rs"] mod sortPrime;
// #[path="sortarea vectorilor/sortareDivizori/sortareDivizori.rs"] mod sortareDivizori;
// #[path="sortarea vectorilor/arhitectura2/arhitectura2.rs"] mod arhitectura2;
// #[path="sortarea vectorilor/kSort/kSort.rs"] mod kSort;
// #[path="sortarea vectorilor/sortMax/sortMax.rs"] mod sortMax;
// #[path="sortarea vectorilor/cifInit/cifInit.rs"] mod cifInit;
// #[path="sortarea vectorilor/sortareCrescatoare/sortareCrescatoare.rs"] mod sortareCrescatoare;
// #[path="sortarea vectorilor/sortareMunte/sortareMunte.rs"] mod sortareMunte;
// #[path="sortarea vectorilor/sortareIntreIndici/sortareIntreIndici.rs"] mod sortareIntreIndici;
// #[path="sortarea vectorilor/sortarePrimaCifra/sortarePrimaCifra.rs"] mod sortarePrimaCifra;
// #[path="sortarea vectorilor/educatieFizica/educatieFizica.rs"] mod educatieFizica;
// #[path="sortarea vectorilor/sortareSumaCifrelor/sortareSumaCifrelor.rs"] mod sortareSumaCifrelor;
// #[path="sortarea vectorilor/sortareNumarDivizori/sortareNumarDivizori.rs"] mod sortareNumarDivizori;
// #[path="vectori unidimensioali/secvente in vectori/secventeDeNumereEgale/secventeDeNumereEgale.rs"] mod secventeDeNumereEgale;
// #[path="vectori unidimensioali/secvente in vectori/secventaDeNumereEgale/secventaDeNumereEgale.rs"] mod secventaDeNumereEgale;
// #[path="vectori unidimensioali/generari siruri/fibonacci/fibonacci.rs"] mod fibonacci;
// #[path="vectori unidimensioali/generari siruri/fibonacci2/fibonacci2.rs"] mod fibonacci2;
// #[path="vectori unidimensioali/generari siruri/fibonacciGeneralizat/fibonacciGeneralizat.rs"] mod fibonacciGeneralizat;
// #[path="vectori unidimensioali/generari siruri/generareSir/generareSir.rs"] mod generareSir;
// #[path="vectori unidimensioali/generari siruri/verificareFib/verificareFib.rs"] mod verificareFib;
// #[path="vectori unidimensioali/parcurgeri/afisare/afisare.rs"] mod afisare;
// #[path="vectori unidimensioali/parcurgeri/afisare2/afisare2.rs"] mod afisare2;
// #[path="vectori unidimensioali/parcurgeri/inlocuire/inlocuire.rs"] mod inlocuire;
// #[path="vectori unidimensioali/parcurgeri/afisare3/afisare3.rs"] mod afisare3;
// #[path="vectori unidimensioali/parcurgeri/afisare4/afisare4.rs"] mod afisare4;
// #[path="vectori unidimensioali/parcurgeri/determinare/determinare.rs"] mod determinare;
// #[path="vectori unidimensioali/parcurgeri/pozitiiMinMax/pozitiiMinMax.rs"] mod pozitiiMinMax;
// #[path="vectori unidimensioali/parcurgeri/determinare2/determinare2.rs"] mod determinare2;
// #[path="vectori unidimensioali/parcurgeri/determinare4/determinare4.rs"] mod determinare4;
// #[path="vectori unidimensioali/parcurgeri/toateDiferite/toateDiferite.rs"] mod toateDiferite;
// #[path="vectori unidimensioali/parcurgeri/esteSirPalindrom/esteSirPalindrom.rs"] mod esteSirPalindrom;
// #[path="vectori unidimensioali/parcurgeri/determinare3/determinare3.rs"] mod determinare3;
// #[path="vectori unidimensioali/parcurgeri/ordonateAlternativ/ordonateAlternativ.rs"] mod ordonateAlternativ;
// #[path="vectori unidimensioali/parcurgeri/existaNumarPerfect/existaNumarPerfect.rs"] mod existaNumarPerfect;
// #[path="vectori unidimensioali/parcurgeri/determinare5/determinare5.rs"] mod determinare5;
// #[path="vectori unidimensioali/parcurgeri/determinare6/determinare6.rs"] mod determinare6;
// #[path="vectori unidimensioali/parcurgeri/estePermutare/estePermutare.rs"] mod estePermutare;
#[path="vectori unidimensioali/parcurgeri/apareOglinditul/apareOglinditul.rs"] mod apareOglinditul;

fn main() {
    println!("Hello, world!");
    // sum::sum();
    // urare::urare();
    // scadere::scadere(50, 20);
    // asii::asii(10, 20);
    // uciv::uciv(25, 78);
    // globuri::globuri(7);
    // copii2::copii2(7, 5, 3);
    // parc2::parc2(3);
    // camioane::camioane(3, 5, 4, 2, 5);

    // let array: [i32; 20] = [438, 712, 229, 301, 61, 409, 948, 508, 901, 789, 388, 495, 848, 180, 376, 790, 700, 939, 436, 929];
    // let array: [i32; 50] = [373, 171, 372, -671, 669, 455, 11, 12, -512, 297, 136, -195, 928, 75, -206, -177, 657, 734, 588, 872, -686, -324, 934, -659, -859, -399, 679, -194, 32, 175, -972, 81, 898, -799, -3, 859, 343, 182, -114, -855, 95, -70, 220, 801, -567, 812, 563, -116, -274, -511];
    // let array: [i32; 30] = [691, 901, 471, 999, 810, 209, 493, 959, 340, 946, 265, 794, 988, 29, 191, 728, 171, 78, 742, 273, 390, 22, 26, 299, 172, 707, 212, 173, 53, 830];
    // ordonare::ordonare(&array, true);
    // sortPrime::sortPrime(&array);
    // sortareDivizori::sortareDivizori();
    // arhitectura2::arhitectura2();
    // kSort::kSort();
    // sortMax::sortMax();
    // cifInit::cifInit();
    // sortareCrescatoare::sortareCrescatoare();
    // sortareMunte::sortareMunte();
    // sortareIntreIndici::sortareIntreIndici();
    // sortarePrimaCifra::sortarePrimaCifra();
    // educatieFizica::educatieFizica();
    // sortareSumaCifrelor::sortareSumaCifrelor();
    // sortareNumarDivizori::sortareNumarDivizori();
    // secventeDeNumereEgale::secventeDeNumereEgale();
    // secventaDeNumereEgale::secventaDeNumereEgale();
    // fibonacci::fibonacci();
    // fibonacci2::fibonacci2();
    // fibonacciGeneralizat::fibonacciGeneralizat();
    // generareSir::generareSir();
    // verificareFib::verificareFib();
    // afisare::afisare();
    // afisare2::afisare2();
    // inlocuire::inlocuire();
    // afisare3::afisare3();
    // afisare4::afisare4();
    // determinare::determinare();
    // pozitiiMinMax::pozitiiMinMax();
    // determinare2::determinare2();
    // determinare4::determinare4();
    // toateDiferite::toateDiferite();
    // esteSirPalindrom::esteSirPalindrom();
    // determinare3::determinare3();
    // ordonateAlternativ::ordonateAlternativ();
    // existaNumarPerfect::existaNumarPerfect();
    // determinare5::determinare5();
    // determinare6::determinare6();
    // estePermutare::estePermutare();
    apareOglinditul::apareOglinditul();
}
